### ISSUE TITLE
Problem with gpt_posterior settings

### ISSUE THREAD

**Issue by jduerholt** [pytorch/botorch#609]
Dear all,

I am testing the newest botorch version from the master branch and I am encountering an error when evaluating the posterior of my model. I get the following error `AttributeError: type object 'debug' has no attribute 'is_default'` in `gpt_posterior_settings`. I can see that this method was changed two days ago by @Balandat.

Switching back to 0.3.2 it still works. See the mwe attached.

I am not sure if it is a bug or I forgot to define a specific variable which is needed in the newest version

Perhaps somebody can help me with this issue ;)

Best,

Johannes
[mwe2.py.txt](https://github.com/pytorch/botorch/files/5572796/mwe2.py.txt)

**Comment by jduerholt** [comment]
I think, I found it ;) The Problem is that changes to the `settings.py` of gpytorch were made which are only in the master branch but not in release 1.2.0 which is specified as needed version for the current botorch. This means that the current master branch of botorch is not working with gpytorch 1.2.0/1.2.1 but only with the current head of the master branch. Perhaps one should catch this somewhere ...

**Comment by Balandat** [comment]
Yeah you're right about this requiring some gpytorch changes that are not in the latest gpytorch release. We often modify things in gpytorch to enable new botorch features, so this is pretty common.  

In general the expectation is for botorch master to be run on gpytorch master, this is also what we suggest in the readme: https://github.com/pytorch/botorch#installing-from-latest-master

Catching this is going to be pretty cumbersome. Maybe there is a way to conditionally add a different gpytorch req in setup.py when using setuptools_scm. But not sure if that's worth the effort at this point...
